In [1]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [4]:
arr2 = np.array([
[1,2,3],
[4,5,6]
])
print(arr2*2)

[[ 2  4  6]
 [ 8 10 12]]


In [6]:
np.ones((6,6))


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.arange(1,20)
arr3 = np.arange(2,21,2)
print(f"{arr3[0]} {arr3[-1]}")



2 20


In [23]:
a = np.arange(1,4)
b = np.arange(4,7)
a + b
a - b
a * b
a / b

array([0.25, 0.4 , 0.5 ])

In [39]:
#arr = np.array([10,20,30,40,50])
arr = np.arange(10,60,10)
arr
#arr = [10, 20, 30, 40, 50]
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())




150
30.0
50
10


In [44]:
arr = np.arange(1,13)
print(arr)
arr2 = arr.reshape(3,4)
print(arr2*2)



[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
